### ISSUE TITLE
Add bindings for GstToc/TocSetter

### ISSUE THREAD

**Issue by sdroege** [sdroege/gstreamer-rs#10]
https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gstreamer/html/GstToc.html
https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gstreamer/html/gstreamer-GstTocSetter.html

The TocSetter should be possible to autogenerate, Toc needs manual code (because miniobject). See e.g. caps.rs, tags.rs, sample.rs.

Needs also addition of support for the event and message

**Comment by fengalin** [comment]
I will work on this one if that's ok with you.

**Comment by sdroege** [comment]
Sure, go ahead :)
