### ISSUE TITLE
Linking statically?

### ISSUE THREAD

**Issue by chocol4te** [sdroege/gstreamer-rs#105]
Hello,

Is there any way to produce completely static binaries with gstreamer-rs?

Thanks :)

**Comment by sdroege** [comment]
This would be feature that would have to be added to https://github.com/alexcrichton/pkg-config-rs, apart from that static linking should work just fine already.

For which platform are you interested in static linking? Android?

**Comment by chocol4te** [comment]
Raspberry Pi, apparently I just need to set some environment variables. Thanks so much :)

**Comment by sdroege** [comment]
Want to share how you're doing that exactly? :)

Keep in mind that for static linking of GStreamer you also need to worry about statically linking the plugins

**Comment by chocol4te** [comment]
The [`pkg-config` docs](https://docs.rs/pkg-config/0.3.11/pkg_config/)  said that exporting `PKG_CONFIG_ALL_STATIC` would pass --static to all libraries, but I just tested it and its still linking dynamically :/

I didn't know about the plugins, thanks :)
