### ISSUE TITLE
g_signal_emit_by_name won't accept correct argument type

### ISSUE THREAD

**Issue by maxmcd** [sdroege/gstreamer-rs#110]
This fails with `BoolError("Incompatible argument types")`
```rust
let opus_caps = gst::Caps::from_str(&rtp_caps_opus).unwrap();
webrtc
    .emit("add-transceiver", &[&3i32, &opus_caps])
    .unwrap();
```
[add-transceiver](https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-bad/html/gst-plugins-bad-plugins-webrtcbin.html#GstWebRTCBin-add-transceiver) accepts direction and caps. 

I've tried a few values for the direction:
```rust
gstreamer_webrtc_sys::GST_WEBRTC_RTP_TRANSCEIVER_DIRECTION_RECVONLY
&(gstreamer_webrtc_sys::GST_WEBRTC_RTP_TRANSCEIVER_DIRECTION_RECVONLY).to_value()
&(gstreamer_webrtc_sys::GST_WEBRTC_RTP_TRANSCEIVER_DIRECTION_RECVONLY
    as gstreamer_webrtc_sys::GstWebRTCRTPTransceiverDirection)
    .to_value(),
// etc....
```
Wondering if I'm missing a way to pass the type.

**Comment by maxmcd** [comment]
Hmm, this issue also might be better suited on `gtk-rs/sys` happy to move it over there if that's suggested.

**Comment by maxmcd** [comment]
fwiw, it sucessfully sets the caps if I simply remove the type check: [object.rs#L888](https://github.com/gtk-rs/glib/blob/126457f60cda2349d1dffa48a55596c0fb3d699a/src/object.rs#L888)

**Comment by sdroege** [comment]
The problem here is that the enum was not included in the bindings. You should now be able to simply use `&gst_webrtc::WebRTCRTPTransceiverDirection::Recvonly`
