### ISSUE TITLE
GstPlayer: Non functional audio visualization API

### ISSUE THREAD

**Issue by philn** [sdroege/gstreamer-rs#111]
The `gst_player::visualizations_get()` function returns a vector of unusable objects. The name and description fields of the C struct should be exposed in the binding I think, or the set_visualization API changed to accept a PlayerVisualization object: https://github.com/sdroege/gstreamer-rs/blob/master/gstreamer-player/src/auto/player.rs#L261

**Comment by sdroege** [comment]
Yes expose those fields

**Comment by philn** [comment]
I just had a quick look at this, does it mean we need public API to access those 2 fields? Right now they're only defined in the C `GstPlayerVisualization` struct. I'm not very familiar with the glib_wrapper magic :)

**Comment by sdroege** [comment]
You would add

```rust
impl PlayerVisualization {
    pub fn name(&self) -> &str {
        [some stuff with CStr]
    }
}
```

in `src/player_visualization.rs`. And then add `mod player_visualization;` to `src/lib.rs`.

**Comment by philn** [comment]
Ok that's what I started already but I was wondering if C API would also be needed.

**Comment by philn** [comment]
Alright, I have something now, patch incoming :)
