### ISSUE TITLE
Assert goes off if you remove a pad in add_probe

### ISSUE THREAD

**Issue by JohanGoversTech** [sdroege/gstreamer-rs#115]
If you use the add_probe function on a pad to remove a pad. The assert will be triggered that the PadProbeId are 0. This should not happen, the 0 is the right return value.

Here a fix for this problem:
[fix_diff.txt](https://github.com/sdroege/gstreamer-rs/files/2101430/fix_diff.txt)

**Comment by sdroege** [comment]
I'm not sure I understand what you're doing. `0` should never be returned AFAIU.

Can you provide a testcase (or even better add a test to `src/pad.rs`)?

**Comment by sdroege** [comment]
Ah I see this from the documentation:

```
When using GST_PAD_PROBE_TYPE_IDLE it can
happen that the probe can be run immediately and if the probe returns
GST_PAD_PROBE_REMOVE this functions returns 0.
```

The correct solution would then be to wrap the return value in an `Option`. Do you want to submit a PR for that?

**Comment by sdroege** [comment]
Reason for `Option` is that it's invalid to pass `0` to any of the other pad probe related functions. It will cause an assertion or warning.

**Comment by JohanGoversTech** [comment]
I have create PR #116 for this.

**Comment by sdroege** [comment]
This is merged now. Thanks again :)
