### ISSUE TITLE
Add bindings for enum types of element properties in pipeline

### ISSUE THREAD

**Issue by js4785** [sdroege/gstreamer-rs#120]
There are missing enum type bindings in regards to `Element`s in a given `Pipeline`.

One problematic example:
```
let queue = gst::ElementFactory::make("queue", "queue")
        .expect("Could not create queue element.");
// queue.set_property("leaky", & ??? .to_value())
//         .expect("Can't set property leaky of queue element");
```
It isn't possible to set the `leaky` property of `queue` because it is of type [`GstQueueLeaky`](https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gstreamer-plugins/html/gstreamer-plugins-queue.html#GstQueueLeaky), which is an enum that doesn't at all exist in `gstreamer-rs` or its associated crates.

However it does (obviously) exist on C-level and gets instantiated at compile-time, and its representation on Rust-level can be easily shown:
```
let leaky_type = queue.get_property("leaky").unwrap().type_();
println!("{:?}", leaky_type);
```
Running `cargo run` would give:
```
GstQueueLeaky
```
but, at least according to my understanding of the docs, I can't use the wrapper `glib::types::Type` around `GstQueueLeaky` to set the value of the enum to something else.

If there are currently ways around this issue, I'd like to know also. Thanks!

**Comment by sdroege** [comment]
You can use

```rust
queue.set_property_from_str("leaky", "upstream");
```

or you can make use of the [`EnumClass`](http://gtk-rs.org/docs/glib/struct.EnumClass.html) API

```rust
let leaky_type = queue.get_property("leaky").unwrap().type_();
let enum_class = glib::EnumClass::new(leaky_type);
let value = enum_class.to_value_by_nick("upstream").unwrap();
queue.set_property("leaky", value);
```

The `EnumClass` bindings allow you to query all available values, etc.

**Comment by js4785** [comment]
Ah, `EnumClass` seems very useful, thanks for the helpful response.
