### ISSUE TITLE
gstreamer-rtsp-server build Error on armv7l (RasperryPI): expected u8, found i8

### ISSUE THREAD

**Issue by meldron** [sdroege/gstreamer-rs#122]
Hi there,

trying to build `gstreamer-rtsp-server` on armv7l (Raspberry PI) fails with the following errors:

```
error[E0308]: mismatched types
   --> gstreamer/src/tags.rs:197:39   
    |
197 |                 ffi::gst_tag_get_type(tag_name.as_ptr() as *const i8)
    |                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected u8, found i8
    |
    = note: expected type `*const u8` 
               found type `*const i8` 

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
error: Could not compile `gstreamer`. 
warning: build failed, waiting for other jobs to finish...
error: aborting due to 4 previous errors

Some errors occurred: E0277, E0308.
For more information about an error, try `rustc --explain E0277`.
error: Could not compile `gio`.
```

I previously reported the error at [gpio](https://github.com/gtk-rs/gio/issues/137), where @sdroege suggested that:
> Somewhere there must be a u8 or i8 instead of c_char
```
error[E0308]: mismatched types
   --> gstreamer/src/tags.rs:197:39   
    |
197 |                 ffi::gst_tag_get_type(tag_name.as_ptr() as *const i8)
    |                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected u8, found i8
    |
    = note: expected type `*const u8` 
               found type `*const i8` 
```

**Comment by sdroege** [comment]
Here the cast should either go away completely, be a `as *const _` (with underscore) or `as *const libc::c_char` otherwise.

Do you want to prepare a PR for this one? The other ones are all in gio and need to be fixed there or in GLib.

**Comment by meldron** [comment]
I will prepare a PR and try to hunt for more this weekend.

Thanks for your help!

**Comment by sdroege** [comment]
The problem was actually a bit deeper, more than a wrong cast. It's fixed here now.

**Comment by meldron** [comment]
Thanks a lot.

I also submitted a [PR](https://github.com/gtk-rs/gio/pull/138) for the gio type problems.
