### ISSUE TITLE
How can I iterate a TagList and print each tag's name and value?

### ISSUE THREAD

**Issue by sbstp** [sdroege/gstreamer-rs#123]
Looking at the TagList API, it doesn't look like it's possible to just iterate over the list and print each tag's name and value. I want to inspect what the tags are and it's just not possible to. to_string can do it, but it's not usable when there's a lot of data.

**Comment by sdroege** [comment]
You can currently do that with `TagList::n_tags()` and `TagList::nth_tag_name()` for the iteration, and then getting each tag by name, or `TagList::iter_tag_list()`.

This API was only added in GIT, it's not part of the 0.11 release
