### ISSUE TITLE
Issue with h264depay and avdec_h264 when using rtpulpfecenc/dec !

### ISSUE THREAD

**Issue by nithin-pradeep786** [sdroege/gstreamer-rs#125]
Hello All,

I am currently working on adding elements **rtpulpfecenc** and **rtpulpfecdec** to my sender and receiver pipelines respectively. The example program for these were written in rust and uses **rtpvp8pay /depay**  along with  **vp8enc** and **vp8dec** . Since my application is only compatible with **rtph264pay/depay** ,I have used ,
**Sender:**
filesrc >> decodebin >> videoconvert >> queue >> rtph264pay >> Queue >> rtpbin ( rtpulpfecenc > rtpsession ) >> udpsink
**Receiver :**
udpsrc>> netsim >>rtpbin ( funnel > rtpsession > rtpstorage > rtpssrcdemux > rtpjitterbuffer > rtpptdemux > rtpulpfecdec ) >> rtph264depay >> h264parse >> capsfilter >> **decodebin** >>videoconvert >> videoscale >> capsfilter >> x264enc >> matroskamux   >> filesink

I am setting the fec percentage as 10 on sender and drop as 1 % on receiver side , I am getting the ratio of packets unrecovered : recovered , But **Issue** is that decode bin at the receiver side uses avdec_h264 internally as decoder , it is producing the following errors,

 _0:00:09.053600607 26017 0x7f7f6c003230 ERROR                  libav :0:: {] Missing reference picture, default is 0
0:00:09.053652680 26017 0x7f7f6c003230 ERROR                  libav :0:: {] decode_slice_header error
0:00:09.118489816 26017 0x7f7f6c003230 ERROR                  libav :0:: {] Missing reference picture, default is 2
0:00:09.641810087 26017 0x7f7f6c003230 ERROR                  libav :0:: {] decode_slice_header error
0:00:09.657737341 26017 0x7f7f6c003230 ERROR                  libav :0:: {] Missing reference_ 

Attached below is the logs related to the same :
[log_with decode bin ERROR .txt](https://github.com/sdroege/gstreamer-rs/files/2261244/log_with.decode.bin.ERROR.txt)

The Dot diagram for the following is also attached :
![server_h264](https://user-images.githubusercontent.com/30233866/43698425-7747723e-9967-11e8-9ae1-85046e14ccb5.png)
![client_h264](https://user-images.githubusercontent.com/30233866/43698452-9417e218-9967-11e8-8986-0d521d4ccc03.png)

_Is there any elements that I  need to add when i use other pay/depay instead of VP8  ,or is this because of any wrong configuration? _
Please Help me with this situation,
**_Eagerly Waiting for a response._** 

Regards,
_Nithin Pradeep_

**Comment by sdroege** [comment]
Hi, thanks for reporting this but this has nothing to do with the GStreamer Rust bindings but with specific GStreamer elements. If you think this is a bug, please report it [in Bugzilla](https://bugzilla.gnome.org/enter_bug.cgi?product=GStreamer), otherwise please discuss it on the [GStreamer mailing list](https://lists.freedesktop.org/mailman/listinfo/gstreamer-devel).
