### ISSUE TITLE
Add bindings for CapsFeatures

### ISSUE THREAD

**Issue by sdroege** [sdroege/gstreamer-rs#13]
https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gstreamer/html/GstCapsFeatures.html

Manually written (because miniobject), see caps.rs, sample.rs, etc.

Support needs to be added to caps.rs

**Comment by sdroege** [comment]
@fengalin maybe you can shortly review the serde implementation, but it's at least backwards compatible :)

**Comment by fengalin** [comment]
@sdroege, yes this is on my TODO list!

**Comment by sdroege** [comment]
Thanks! Did you also get my mail from earlier this week?

**Comment by fengalin** [comment]
Yes, thanks. I'll register ASAP.

**Comment by fengalin** [comment]
> @fengalin maybe you can shortly review the serde implementation

LGTM :)

**Comment by sdroege** [comment]
Thanks :)
