### ISSUE TITLE
rtpfec example causes h264 artifacts with FEC overhead > 0 and netsim = 0

### ISSUE THREAD

**Issue by alexagv** [sdroege/gstreamer-rs#135]
When changing the vp8enc to x264enc and rtpvp8pay to rtph264pay the FEC overhead causes artifacts on receiving stream despite netsim = 0 (no network loss). 
Tried with multiple bitrates and GOP lengths. When FEC = 0 everything is fine, but from 1 to 100, artifacts appear

Tested on: 
macOS High Sierra and Ubuntu 18.04, both running gstreamer 1.14.4

Code:
https://github.com/alexagv/gstreamer-rs/blob/h264-fec/examples/src/bin/rtpfecclient.rs
https://github.com/alexagv/gstreamer-rs/blob/h264-fec/examples/src/bin/rtpfecserver.rs

Picture of stream with FEC=1, netsim=0.0:
<img width="1974" alt="fec-bug-h264" src="https://user-images.githubusercontent.com/10421967/47142522-52898500-d2c3-11e8-9997-a8b96e416c02.png">

**Comment by sdroege** [comment]
This seems like a bug in GStreamer and not in this example or the bindings. Please report here: https://bugzilla.gnome.org/enter_bug.cgi?product=GStreamer
