### ISSUE TITLE
Examples always need gstreamer-rtsp-server-sys

### ISSUE THREAD

**Issue by heftig** [sdroege/gstreamer-rs#136]
The examples currently always depend on `gstreamer-rtsp-server-sys`, even if the `gst-rtsp-server*` features aren't activated. As I don't have `gstreamer-rtsp-server` installed, this fails the build for me.

**Comment by sdroege** [comment]
Do you want to provide a PR for this? Just has to be marked optional in the Cargo.toml

**Comment by heftig** [comment]
What about removing it? Shouldn't the transient dep in `gstreamer-rtsp-server/Cargo.toml` be enough?

**Comment by heftig** [comment]
Mind I can't test if the feature still works post-PR.

**Comment by sdroege** [comment]
It's required because it's directly used from the rtsp-record example

**Comment by sdroege** [comment]
And travis will test all combinations for you :)
