### ISSUE TITLE
Make global pb_utils_get_codec_description a method on GstCaps

### ISSUE THREAD

**Issue by charlie-ht** [sdroege/gstreamer-rs#140]
`pb_utils_get_codec_description` is associated with a caps object, it would perhaps be a bit cleaner if this was a method available on fixed caps types rather than as a global.

**Comment by sdroege** [comment]
Should probably also check other functions like this. E.g. in `gstreamer-video` the event/message functions.

**Comment by sdroege** [comment]
This is now tracked at https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/issues/140
