### ISSUE TITLE
Basic Tutorial 3 Does Not Run On OS X

### ISSUE THREAD

**Issue by raytiley** [sdroege/gstreamer-rs#146]
Tutorial 1 and 2 run find but looks like with tutorial 3 the attatched signal for pad added never gets called. Is it possible this is Os specific?

```
Pipeline state changed from Null to Ready
Received new pad src_0 from test-pipeline
It has type video/x-raw which is not raw audio. Ignoring.
Error received from element Some("/GstPipeline:test-pipeline/GstURIDecodeBin:source/GstSoupHTTPSrc:source") Internal data stream error.
Debugging information: Some("gstbasesrc.c(3055): void gst_base_src_loop(GstPad *) (): /GstPipeline:test-pipeline/GstURIDecodeBin:source/GstSoupHTTPSrc:source:\nstreaming stopped, reason not-linked (-1)")
```

**Comment by sdroege** [comment]
Funny one. Can you attach a debug log with `GST_DEBUG=6`?

**Comment by raytiley** [comment]
https://gist.github.com/raytiley/8dc10a6562953108f55d3fe37a147c4f

**Comment by sdroege** [comment]
You can don't have vorbisdec installed, that's why there's never an audio stream added and only the video stream. And we don't link the video stream, that's why it fails like that.

There's not a lot of error handling in those tutorials to keep them simple

**Comment by raytiley** [comment]
Thanks... Feel like an idiot for not catching that. Saw that basic-tutorial-1 worked and didn't notice that one does video the other audio. Thanks!

**Comment by sdroege** [comment]
No worries, it's far from obvious from the error :)
