### ISSUE TITLE
gstreamer-1.14.4 on macOS high sierra library linking issue

### ISSUE THREAD

**Issue by terminalRoot** [sdroege/gstreamer-rs#152]
I've installed the GStreamer packages following the README from https://github.com/sdroege/gstreamer-rs/commit/d3c586633d4f6397deb31fc7570173c440265eb7
I downloaded  gstreamer-1.0-1.14.4-x86_64.pkg and gstreamer-1.0-devel-1.14.4-x86_64.pkg packages and it's installed at /Library/Frameworks/GStreamer.framework/

1. Cannot find the SDK tutorials folder /Library/Frameworks/GStreamer.framework/Current/share/gst-sdk/tutorials
2. Added the header search path in XCode (10.1), the header file <gst/gst.h> is included, but when I try to use any functions (gst_init(&argc, &argv)) it's throwing linking error- Undefined symbols for architecture x86_64:
  "_gst_init", referenced from:
      _main

3. I've also added the library path Search Paths -> Library Search Paths (/Library/Frameworks/GStreamer.framework/Libraries), still same issue...

**Comment by sdroege** [comment]
This seems to have nothing to do with the GStreamer Rust bindings. Please report this against GStreamer itself at https://gitlab.freedesktop.org/gstreamer
