### ISSUE TITLE
Example for giostreamsink

### ISSUE THREAD

**Issue by sameer** [sdroege/gstreamer-rs#153]
I am trying to stream the output of gstreamer in an HTTP request.

Is there an example for how to use an in-memory sink? I'm following the `encodebin.rs` example and trying to replace `filesink` with `giostreamsink`, but I don't see how you should keep an in-memory buffer to set as the stream destination -- is it supposed to be a Vec with a `vec as *mut u8` or something like that?

**Comment by sdroege** [comment]
An issue tracker is no support forum, and `gstreamer-rs` has also moved to https://gitlab.freedesktop.org/gstreamer/gstreamer-rs :)

Take a look at the `appsink` example, that's probably closer to what you want.

**Comment by sameer** [comment]
> An issue tracker is no support forum, and `gstreamer-rs` has also moved to https://gitlab.freedesktop.org/gstreamer/gstreamer-rs :)
> 
> Take a look at the `appsink` example, that's probably closer to what you want.

Thanks for the suggestion, I'll look into it.
