### ISSUE TITLE
Error: invalid option: --with-orc

### ISSUE THREAD

**Issue by AlexanderKozhevin** [sdroege/gstreamer-rs#155]
Trying to install on OSX Mojave. 
And getting an error. 

```
Error: invalid option: --with-orc
```

**Comment by sdroege** [comment]
Please see the comment at the top of the README.md :) This is only a mirror, the proper place for reporting issues is at https://gitlab.freedesktop.org/gstreamer/gstreamer-rs

Please report this in gitlab, thanks!
