### ISSUE TITLE
gst_buffer_get_reference_timestamp_meta API

### ISSUE THREAD

**Issue by sklose** [sdroege/gstreamer-rs#156]
Hi,

I am trying to use the gst_buffer_get_reference_timestamp_meta C API from Rust, but I can't find it on the BufferRef struct. Is this supported by the Rust bindings?

This is the C code that I am trying to convert to Rust (it's supposed to extract a custom NTP timestamp from a buffer):

```C
GstReferenceTimestampMeta *tsmeta = gst_buffer_get_reference_timestamp_meta(buffer, gst_caps_from_string("ANY"));
  struct timeval             tstv = {0, 0};
  tstv.tv_sec = tsmeta->timestamp;
  tstv.tv_usec = tsmeta->duration;
```

So far I got this Rust code in a callback from an appsink element

```Rust
    sink.set_callbacks(
        gst_app::AppSinkCallbacks::new()
            .new_sample(|appsink| {
                let sample = appsink.pull_sample().ok_or(gst::FlowError::Eos)?;
                let buffer = sample.get_buffer().ok_or_else(|| {
                    gst::gst_element_error!(
                        appsink,
                        gst::ResourceError::Failed,
                        ("Failed to get buffer from appsink")
                    );

                    gst::FlowError::Error
                })?;
                let timestamp = buffer.????;
                Ok(gst::FlowSuccess::Ok)
            }).build());
```

**Comment by sdroege** [comment]
Please see the comment at the top of the README.md :) This is only a mirror, the proper place for reporting issues is at https://gitlab.freedesktop.org/gstreamer/gstreamer-rs

That said, the bindings don't support this meta yet but it would be easy to add. See `src/meta.rs` for the parent buffer meta. Basically the same.

Please create an issue in gitlab, or even better a merge request (let me know if you are planning to work on this). Thanks!

**Comment by sdroege** [comment]
Actually I just noticed that I need it myself for a project. I'll add support for it tomorrow.

Good timing!

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by sdroege** [comment]
See https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/merge_requests/302
