### ISSUE TITLE
debug_set_default_threshold not callable before init

### ISSUE THREAD

**Issue by heftig** [sdroege/gstreamer-rs#157]
`gstreamer::debug_set_default_threshold` panics if `gstreamer::init` has not been called.

But the logging subsystem should be able to be configured before calling `init`.

(The panic message calls it `gst::init` which should probably be fixed, too.)

**Comment by heftig** [comment]
Ah, darn, forgot this got moved, sorry.

**Comment by sdroege** [comment]
Just send a MR for this :)
