### ISSUE TITLE
docs.rs documentation has not build since 0.15.0

### ISSUE THREAD

**Issue by martijnberger** [sdroege/gstreamer-rs#163]
https://docs.rs/crate/gstreamer/0.15.0/builds/206482

`[INFO] [stderr] error: couldn't read ../docs/gstreamer/docs.md: No such file or directory (os error 2)
[INFO] [stderr]   --> build.rs:22:20
[INFO] [stderr]    |
[INFO] [stderr] 22 |         let docs = include_str!("../docs/gstreamer/docs.md");
[INFO] [stderr]    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[INFO] [stderr] 
[INFO] [stderr] error: aborting due to previous error`

**Comment by sdroege** [comment]
Wrong repository, this is only a mirror :) But see https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/-/issues/258 . I'll fix this before the next release.
