### ISSUE TITLE
.set_state not found in auto::element::Element

### ISSUE THREAD

**Issue by michaeldavidjohnson** [sdroege/gstreamer-rs#168]
```
let pipestring = format!("filesrc location='{}' ! decodebin ! videoconvert ! autovideosink",filepath);
let pipeline  = gstreamer::parse_launch(&pipestring).unwrap();
```

Here pipeline returns auto::element::Element which does not have set_state as a method. The major issue with this is I can't even find auto::element::Element in the docs so I don't know what I'm messing up.

Any help would be much appreciated

**Comment by sdroege** [comment]
You need to `use gst::prelude::*` or at least `gst::ElementExtManual`, see the examples in the examples directory.
