### ISSUE TITLE
HELP: Changing audio / subtitle track from parse_launch

### ISSUE THREAD

**Issue by IguanasInPyjamas** [sdroege/gstreamer-rs#169]
The issue stems from the omission of the playback tutorials from the C gstreamer to this repo.

The C gstreamer contains elements that I can't find in the docs such as the flags which dictate changing audio and subtitle streams and the docs are fairly bare outside the pure basics so it's hard to see what's going on, the lack of Signals in the rust docs could also be causing the issue here too.

Can you please point me in the right direction?

**Comment by sdroege** [comment]
I'm not entirely sure what you're looking for, can you give some more details?

Also let's continue the discussion on the mailing list: https://lists.freedesktop.org/mailman/listinfo/gstreamer-devel

With regard to flags, maybe this tutorial code will help you? https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/-/merge_requests/172

**Comment by IguanasInPyjamas** [comment]
Yes I can give you more details, i've sent an email on the mailing list hopefully it went through
