### ISSUE TITLE
Help: I'm trying to use VideoOverlay::set_window_handle with a winit window created with glutin, but instead of playing the video in the winit window it creates a new window

### ISSUE THREAD

**Issue by WuChanGG** [sdroege/gstreamer-rs#170]
I have this code
```        unsafe {
            let rwh = display.gl_window().window().raw_window_handle();
            let hwnd = match rwh {
                raw_window_handle::RawWindowHandle::Windows(windows_handle) => Some(windows_handle.hwnd),
                _ => None
            };
            video_overlay.set_window_handle(hwnd.unwrap() as usize);
        }
```
And I'm trying to do what the next code does:
```                        let xid = gdk_x11_window_get_xid(gdk_window.as_ptr() as *mut _);
                        video_overlay.set_window_handle(xid as usize);
                    }
```
In my code (first block) I have a winit window created with `glutin`, in the second block of code it is a X11 window, however when I call `set_window_handle`, (i guess gstreamer) creates a new window instead of using the `winit` window provided to play the video there, I was wondering if there was some way to hook the player (VideoOverlay) to the `winit` window or if I'm misunderstanding something. Hope this is enough info, if not I could share the code of the project.

**Comment by sdroege** [comment]
Let's discuss this in more detail on the mailing list: https://lists.freedesktop.org/mailman/listinfo/gstreamer-devel
Please also include your code and ideally a self-contained, runnable testcase in there.

You need to set the window handle before the pipeline starts, or at very latest from a sync (!) bus handler when the `prepare-window-handle` message is received.
