### ISSUE TITLE
video-direction (GstVideoOrientationMethod) property of videoflip element can't be set

### ISSUE THREAD

**Issue by JensNeumannZAL** [sdroege/gstreamer-rs#171]
Hey,

I am creating a "videoflip" element for my pipeline:

```
use gst::prelude::*;
use gst_video::VideoFormat;
use ffi;

let met : ffi::GstVideoOrientationMethod = ffi::GST_VIDEO_ORIENTATION_VERT;
let flipper = gst::ElementFactory::make("videoflip", Some("flipper"))
.expect("Could not create flipper element.");
flipper.set_property("video-direction", &met)
.expect("Could not set property.");
```

The problem is:
`thread 'main' panicked at 'Could not set property.: BoolError { message: "property \'video-direction\' of type \'GstVideoFlip\' can\'t be set from the given type (expected: \'GstVideoOrientationMethod\', got: \'gint\')"`

Apparently the GstVideoOrientationMethod is cast as an int and given to the video-direction property which refuses it because it expects a GstVideoOrientationMethod (which I tried giving it in the first place).

I'm not a Rust expert but I assume the problem lies here: https://gstreamer.pages.freedesktop.org/gstreamer-rs/src/gstreamer_video_sys/lib.rs.html#332
In this library (which I import as ffi), the GstVideoOrientationMethod is specified, but as an int.

So I don't want to rule out that I did something wrong here, but this looks like a bug. It appears to be impossible to set this property here.

Best regards

**Comment by sdroege** [comment]
See https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/-/merge_requests/704 . With that you can do `flipper.set_property("video-direction", &gst_video::VideoOrientationMethod::Vert)` and similar.

Before that you can make use of the [`glib::EnumClass`](https://gstreamer.pages.freedesktop.org/gstreamer-rs/glib/struct.EnumClass.html) API, or simply do `flipper.set_property_from_str("video-orientation", "vert")`.

Also this repository here is only a mirror of https://gitlab.freedesktop.org/gstreamer/gstreamer-rs :)

**Comment by JensNeumannZAL** [comment]
Thanks a lot for your quick response, I really didn't know about the set_property_from_str option! It doesn't seem to have an "expect" function though, to check if it worked. Also, it's great that you fixed this part in the code as well.

By the way, if anyone else reads this, the property name is not "video-orientation", but "video-direction". Otherwise the command won't work.

**Comment by sdroege** [comment]
> It doesn't seem to have an "expect" function though, to check if it worked.

Ideally we would implement this in Rust in the bindings instead of just calling into C. That way it would be possible to check if the property exists, etc.

Note that setting properties can't fail unless you typo the property name, provide a value of a wrong type or a value out of range for the property.

> By the way, if anyone else reads this, the property name is not "video-orientation", but "video-direction". Otherwise the command won't work.

Indeed, or you use the (now bound) `gst_video::VideoDirection` interface :)
