### ISSUE TITLE
Adding request ghost pad for bin

### ISSUE THREAD

**Issue by Townsheriff** [sdroege/gstreamer-rs#172]
Hi,

I'm creating a bin that uses concat plugin as an input for new media feeds. When I want to append a video fragment, I need to request a pad from concat and link it to my video source element. 

I know how to link a static pad or how to forward sometimes pad, but I cannot find any documentation for how to dynamically link request pad template to the bin.

I thought there would be some mechanism with ghost pads where I would pass request pad template, the name of the pad and it will do the linking on its own, and it would allow me to remove the pads when I dont need them anymore, but when trying to request pad from the bin it returns None.

Code for attempting to link ghost pad to request pad template:
```
let concat_sink_pad = concat.get_pad_template("sink_%u").unwrap();
let ghost_sink_pad = gst::GhostPad::builder_with_template(&concat_sink_pad, Some("sink_%u")).build();
bin.add_pad(&ghost_sink_pad).unwrap();
```

Code for linking with static pad:
```
let concat_sink_pad = concat.get_request_pad("sink_%u").unwrap();
let ghost_sink_pad = gst::GhostPad::builder(Some("sink"), gst::PadDirection::Sink)
        .build_with_target(&concat_sink_pad).unwrap();
 bin.add_pad(&ghost_sink_pad).unwrap();
```

Currently my only solution is to add new static pads when I need them. Any suggestions on how should I approach this or where should I look for information?

Thank you!

**Comment by sdroege** [comment]
This repository is only a mirror. The canonical location of this repository is here: https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/

For getting help with GStreamer (and the Rust bindings), best to ask either on the [mailing list](https://lists.freedesktop.org/mailman/listinfo/gstreamer-devel) or on the [GNOME discourse](https://discourse.gnome.org). Issue trackers are not support forums :)

> Currently my only solution is to add new static pads when I need them.

That's a valid approach and whether this is the easiest and makes sense depends on your application.

> but when trying to request pad from the bin it returns None.

That requires you to implement a subclass of `gst::Bin` and use that here. That subclass will have to implement at least `gst::ElementImpl::request_new_pad()`, which will then be called by `gst::Element::get_request_pad()`.

You can find an example [here](https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs/-/blob/5dd0a23986352fa363b002c8495951e6a3593673/utils/togglerecord/src/togglerecord/imp.rs#L1896-1985).
