### ISSUE TITLE
More detailed installation instructions

### ISSUE THREAD

**Issue by burnzzz** [sdroege/gstreamer-rs#177]
Hi Sebastian,

I´m a complete Rust noob, but still would like to use the fallbackswitch plugin you describe in your blogpost:
https://coaxion.net/blog/2020/07/automatic-retry-on-error-and-fallback-stream-handling-for-gstreamer-sources

So I came here and followed the installation process, but it seems, that there are some details missing, that might be obvious to any experienced Rust developer. So I can compile the bindings without error, using `cargo build --release`  but then I´m not sure how to continue. In the blogpost you say:
`Once that is done, compiling is mostly a matter of running cargo build in the utils/fallbackswitch directory and copying the resulting libgstfallbackswitch.so (or .dll or .dylib) into one of the GStreamer plugin directories, for example ~/.local/share/gstreamer-1.0/plugins.`

But I cannot find any *.so libraries in `target/release` except in `./target/release/deps`, which is not what I need, right? 
So maybe you could hint me, what the install process looks like after successful compilation on Linux/ubuntu 20.04.

**Comment by sdroege** [comment]
Check the instructions in the gst-plugins-rs repository: https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs#building
