### ISSUE TITLE
Example of reading an RTSP stream?

### ISSUE THREAD

**Issue by sgasse** [sdroege/gstreamer-rs#178]
Hi! I stumbled over this repository in search of an example for **reading** an RTSP stream in Rust. I found the [rtsp-server](https://github.com/sdroege/gstreamer-rs/blob/master/examples/src/bin/rtsp-server.rs) example, but that seems to do the inverse of what I want.

Let's say we have an RTSP stream already served. In Python/OpenCV, I'd use a link like this to connect:
```
rtsp://name:password@1.2.3.4:port
```

Could I use `gstreamer-rs` to read individual frames from such a link in Rust? Would you have an example that you could point me to?

**Comment by sdroege** [comment]
Take a look at any of the playback examples, and the `appsink` example (which gets data buffer by buffer from the pipeline).

If you have more questions, please ask on the [GNOME discourse](https://discourse.gnome.org/) or the [GStreamer mailing list](https://lists.freedesktop.org/mailman/listinfo/gstreamer-devel).

**Comment by sgasse** [comment]
Ah thank you @sdroege - [`appsink`](https://github.com/sdroege/gstreamer-rs/blob/master/examples/src/bin/appsink.rs) looks like what I have been searching for! :slightly_smiling_face: 

I will head for the discourse forum if I run into issues. And thank you and the other contributors for the great, clear example of using `gstreamer` in Rust :+1:
