### ISSUE TITLE
https://gstreamer.freedesktop.org/documentation/tutorials/basic/short-cutting-the-pipeline.html?gi-language=c

### ISSUE THREAD

**Issue by jaiminlee** [sdroege/gstreamer-rs#183]
basic-tutorial-8.c link error

Hello. Sir

Help me

How to build basic-tutorial-8.c?

./build.sh
gcc basic-tutorial-8.c -o basic-tutorial-8 `pkg-config --cflags --libs gstreamer-1.0 gstreamer-audio-1.0`

basic-tutorial-8.c: In function ‘main’:
basic-tutorial-8.c:190:19: warning: implicit declaration of function ‘gst_element_request_pad_simple’; did you mean ‘gst_element_request_pad’? [-Wimplicit-function-declaration]
  190 |   tee_audio_pad = gst_element_request_pad_simple (data.tee, "src_%u");
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                   gst_element_request_pad
basic-tutorial-8.c:190:17: warning: assignment to ‘GstPad *’ {aka ‘struct _GstPad *’} from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  190 |   tee_audio_pad = gst_element_request_pad_simple (data.tee, "src_%u");
      |                 ^
basic-tutorial-8.c:193:17: warning: assignment to ‘GstPad *’ {aka ‘struct _GstPad *’} from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  193 |   tee_video_pad = gst_element_request_pad_simple (data.tee, "src_%u");
      |                 ^
basic-tutorial-8.c:196:15: warning: assignment to ‘GstPad *’ {aka ‘struct _GstPad *’} from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  196 |   tee_app_pad = gst_element_request_pad_simple (data.tee, "src_%u");
      |               ^
/usr/bin/ld: /tmp/ccIE9cOW.o: in function `main':
basic-tutorial-8.c:(.text+0xb2a): undefined reference to `gst_element_request_pad_simple'
/usr/bin/ld: basic-tutorial-8.c:(.text+0xb8e): undefined reference to `gst_element_request_pad_simple'
/usr/bin/ld: basic-tutorial-8.c:(.text+0xbf2): undefined reference to `gst_element_request_pad_simple'
collect2: error: ld returned 1 exit status

Could you solve it?

Thank you.
jaimin

**Comment by sdroege** [comment]
This repository is for the GStreamer Rust bindings and you're asking about how to compile C code. Your question is answered by https://gitlab.freedesktop.org/gstreamer/gst-docs/-/issues/91
