### ISSUE TITLE
Module name changed to gstreamer?

### ISSUE THREAD

**Issue by minato-ellie** [sdroege/gstreamer-rs#187]
After modifying all 'gst' to 'gstreamer', the program runs normally. 
Codes in the tutorial may need to be updated. Should I create a PR?

https://github.com/sdroege/gstreamer-rs/blob/49bf6042768439be8270e66bc29a4a022c64cb1c/tutorials/src/bin/basic-tutorial-7.rs#L1

**Comment by sdroege** [comment]
That's taken care of by `Cargo.toml` already:

https://github.com/sdroege/gstreamer-rs/blob/49bf6042768439be8270e66bc29a4a022c64cb1c/examples/Cargo.toml#L11

Also this repo is only a mirror, the correct location is at https://gitlab.freedesktop.org/gstreamer/gstreamer-rs :)
