### ISSUE TITLE
Restart recording tee branch

### ISSUE THREAD

**Issue by Maobuff** [sdroege/gstreamer-rs#188]
I'm trying to implement splitting record files with such a pipeline
`source->tee->queue1->encoder->filesink`
`           ->queue2->visualization`
Previously I used add_probe on the src pad of tee with GST_PAD_PROBE_TYPE_IDLE to unlink it from sinkpad of queue1 and send eos to the encoder. Then i have to catch element msg on the bus from filesink to properly close the queue1 branch.
I can't see a way to pass the encoder element to add_probe callback. How to properly implement such a task in rust.

**Comment by sdroege** [comment]
A better place to ask this would be https://discourse.gstreamer.org . Thanks!

This repository is only a mirror (and the original location) of https://gitlab.freedesktop.org/gstreamer/gstreamer-rs
