### ISSUE TITLE
Glib2.0 needs to be cross compiled with mipsel(32-bit little endian) architecture

### ISSUE THREAD

**Issue by Shahmeera** [sdroege/gstreamer-rs#189]
I want to cross compile glib2.0 with mipsel(32-bit little endian) architecture. For that I have downloaded source code from
https://docs.gtk.org/glib/ and tried to cross compile using this , but I am getting errors like : cpu_family =mipsel and system = linux are not the perfect match and with that so many compatibility errors. My  cross-file cross_file.txt for cross compilation is as below

[host_machine]
system = 'linux'
cpu_family = 'mipsel'
cpu = 'mipsel'
endian = 'little'

[binaries]
c = '/opt/mips32el--glibc--stable-2020.02-1/bin/mipsel-linux-gcc'
cpp = '/opt/mips32el--glibc--stable-2020.02-1/bin/mipsel-linux-g++'
ar = '/opt/mips32el--glibc--stable-2020.02-1/bin/mipsel-linux-ar'
ld = '/opt/mips32el--glibc--stable-2020.02-1/bin/mipsel-linux-ld'
objcopy = '/opt/mips32el--glibc--stable-2020.02-1/bin/mipsel-linux-objcopy'
strip = '/opt/mips32el--glibc--stable-2020.02-1/bin/mipsel-linux-strip'
RANLIB='/opt/mips32el--glibc--stable-2020.02-1/bin/mipsel-linux-ranlib'
pkg-config = '/opt/mips32el--glibc--stable-2020.02-1/bin/mipsel-linux-pkg-config'

**Comment by sdroege** [comment]
This is a general environment setup problem and you probably have better luck at a place specific to your toolchain. I see you also asked this at https://discourse.gnome.org/t/glib2-0-needs-to-be-cross-compiled-with-mipsel-32-bit-little-endian-architecture/19069 , which is already a better place.

This repository is only a mirror of the GStreamer Rust bindings, and has no relation at all to your problem.
