### ISSUE TITLE
expected: 'guint', got: 'gint' when setting parameters

### ISSUE THREAD

**Issue by Elpersonn** [sdroege/gstreamer-rs#190]
`thread 'main' panicked at src/main.rs:86:16:
property 'target-duration' of type 'GstHlsSink' can't be set from the given type (expected: 'guint', got: 'gint')
`
```
    hlselement.set_property("target-duration", 3);
```
doing `as u32` doesn't fix it
does `as u64` makes it guint64

**Comment by sdroege** [comment]
`3u32` will fix it. How does it still fail then?

But also wrong place to ask this question :) Please ask at https://discourse.gstreamer.org/
