### ISSUE TITLE
Possible incompleteness

### ISSUE THREAD

**Issue by YichiZhang0613** [sdroege/gstreamer-rs#191]
In gstreamer-rs/gstreamer/src/value.rs, the comment indicates that there is a constraint denom != 0, while the code doesn't check it. I think there should be assert_ne!(denom, 0);
```rust
    /// # Panics
   ///
    /// Panics if `denom` is zero.
    #[inline]
    pub fn new(numer: i32, denom: i32) -> Self {
        skip_assert_initialized!();
        (numer, denom).into()
    }
```

**Comment by sdroege** [comment]
Wrong repository, this is just a mirror of the correct one.

But this is checked a few layers down in https://docs.rs/num-rational/latest/num_rational/struct.Ratio.html#method.new
