### ISSUE TITLE
Cargo ndk with ld failed?

### ISSUE THREAD

**Issue by cxg666** [sdroege/gstreamer-rs#192]
= note: ld: error: unable to find library -lgstaudio-1.0           ld: error: unable to find library -lgstapp-1.0           ld: error: unable to find library -lgstbase-1.0           ld: error: unable to find library -lgobject-2.0           ld: error: unable to find library -lgio-2.0           ld: error: unable to find library -lgstreamer-1.0           ld: error: unable to find library -lgobject-2.0           ld: error: unable to find library -lgobject-2.0           ld: error: unable to find library -lglib-2.0           clang-14: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by cxg666** [comment]
With self built gstreamer so, and configured pkgconfig, 
Here is pkgconfig result for : **pkg-config --libs --cflags gstreamer-1.0**

-pthread -I/home/jan/devel/gstreamer/cerbero/build/dist/android_universal/arm64/include/gstreamer-1.0 -I/home/jan/devel/gstreamer/cerbero/build/dist/android_universal/arm64/include -I/home/jan/devel/gstreamer/cerbero/build/dist/android_universal/arm64/include/glib-2.0 -I/Users/ryan/wkspace/rust/MiniGameHost/host/src/main/rust/media/media_backends/gstreamer/libs/gst-build-arm64-v8a/glib-2.0/include -L/Users/ryan/wkspace/rust/MiniGameHost/host/src/main/rust/media/media_backends/gstreamer/libs/gst-build-arm64-v8a -lgstreamer_android

**Comment by cxg666** [comment]
Here is my Cargo.toml:

I am not sure why the ndk clang link still have -lgstreamer-android, -lgst-audio-1.0 etc,. These all should pointed to the lgstreamer_android according their pc files, right?

**Cargo.toml**
glib = "0.19"
glib-sys = "0.19"
gst = { package = "gstreamer", version = "0.22" }
gst-app = { package = "gstreamer-app", version = "0.22" }
gst-audio = { package = "gstreamer-audio", version = "0.22" }
gst-base = { package = "gstreamer-base", version = "0.22" }
gstreamer-sys = "0.22"

**Link commands snippet:**
"-Wl,-Bdynamic" "-llog" "-landroid" "-ldl" "-lgstaudio-1.0" "-lgstreamer_android" "-lgstapp-1.0" "-lgstreamer_android" "-lgstbase-1.0" "-lgstreamer_android" "-lgobject-2.0" "-lgio-2.0" "-lgstreamer_android" "-lgstreamer-1.0" "-lgstreamer_android" "-lgobject-2.0" "-lgstreamer_android" "-lgobject-2.0" "-lglib-2.0" "-lgstreamer_android" "-ldl" "-llog" "-lunwind" "-ldl" "-lm" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-z,noexecstack" "-L" "/Users/ryan/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-linux-android/lib" "-o" "/Users/ryan/wkspace/rust/MiniGameHost/host/src/main/rust/target/aarch64-linux-android/debug/deps/libcore.so" "-Wl,--gc-sections" "-shared" "-Wl,-z,relro,-z,now" "-nodefaultlibs"

**Comment by sdroege** [comment]
This repository is only a mirror of the real one, and this issue is already tracked here: https://gitlab.freedesktop.org/gstreamer/gstreamer/-/issues/2999

In summary, you'll need to do a bit of manual work to get things building right now but it's possible and there is a plan how this can be improved but someone needs to actually implement that.
