### ISSUE TITLE
RTSP example only works with videotestsrc?

### ISSUE THREAD

**Issue by overheat** [sdroege/gstreamer-rs#193]
Hi,

`cargo run --bin rtsp-server --features="rtsp-server" -- "videotestsrc ! x264enc ! rtph264pay name=pay0 pt=96"` works.
But
`cargo run --bin rtsp-server --features="rtsp-server" -- "v4l2src device=/dev/video0 ! video/x-raw,format=YUY2,width=640,height=480,framerate=30/1 ! x264enc ! h264parse ! rtph264pay name=pay0 pt=96"` not works.

I am a newbie with Gstreamer. 
Cloud you kindly try the second one on Linux?I test is on my Ubuntu laptop PC.

**Comment by sdroege** [comment]
Please ask on https://discourse.gstreamer.org
