### ISSUE TITLE
Integration with OpenCV Rust

### ISSUE THREAD

**Issue by suryan-s** [sdroege/gstreamer-rs#194]
How could we create a gstream pipeline for opencv rust for obtaining the source from a rtsp stream?

I have tried the standard pipeline for adding the source to opencv like this:
```
pipeline = format!(
                    "rtspsrc location={} latency=200 ! queue ! rtph264depay ! h264parse ! avdec_h264 ! videoconvert ! appsink",
                    path
                );
```

is there any other way to integrate the gstream with opencv?

**Comment by sdroege** [comment]
A better place to ask this would be https://discourse.gstreamer.org . Thanks!

This repository is only a mirror (and the original location) of https://gitlab.freedesktop.org/gstreamer/gstreamer-rs
