### ISSUE TITLE
Fallbacswitch - error in switching pipelines

### ISSUE THREAD

**Issue by AdrianaMiu** [sdroege/gstreamer-rs#197]
Hello!
I'm experiencing challenges when utilizing the fallbackswitch element in my GStreamer pipeline. The intended function is to switch between a primary and fallback video source seamlessly if the primary source becomes unavailable. However, several issues have been observed that may need improvement in fallbackswitch's design or handling:

Expected Behavior
The fallbackswitch element should:

Detect the primary source’s failure and automatically switch to the fallback source after the specified timeout.
Revert back to the primary source if it becomes available again, ensuring minimal delay and visual interruption.
Seamlessly integrate with common elements such as videotestsrc, uridecodebin, videoconvert, and  sink element like rtmpsink.

Observed Behavior
When using fallbackswitch in conjunction with a primary and fallback videotestsrc, several issues arise:

 Switching Delay: The switch from the primary to fallback source often incurs an extended delay, even with a short timeout property set on fallbackswitch, but in finally it doesn't work properly. Just the first source it's working, but switching on the second one it doesn't work.
Reversion Challenges: When the primary source resumes, fallbackswitch does not revert as expected, leading to unexpected behavior or continuous use of the second sourcde, but without any warning or errors messages.
Handling errors: When  it switches to the secondary pipeline, it's working for like maximum 10 seconds and then it stops the pipeline.

Steps to Reproduce

      Create a GStreamer pipeline using the fallbackswitch element with uridecodebin3 for both primary and fallback sources, which are rtsp sources.
      Set a short timeout property  of 5 seconds on fallbackswitch. 
      Manually stop the primary source to trigger the fallback mechanism.      
      Observe the transition and reversion behavior when the primary source is restarted.

Environment
      GStreamer Version: e.g., 1.22
      Platform: e.g., Ubuntu 20.04
      The pipeline is running on a docker container, Docker 27.0.3

Additional Information
It would be beneficial if fallbackswitch could:

      Provide more consistent behavior in switching without introducing delays or visual artifacts.
      Improve reversion logic to detect when the primary source has stabilized and switch back automatically.
      Better compatibility with common downstream elements (e.g., decodebin, videoconvert) used in UI and multimedia applications.

How do i use it:
gst-launch-1.0 
uridecodebin uri=rtsp://<primary_rtsp_stream> name=source_primary ! 
queue ! tee name=tee 

// Audio Visualization Branch 
tee. ! queue ! audioconvert ! audioresample ! capsfilter caps="audio/x-raw, channels=2, rate=32000" ! 
audioamplify ! level ! monoscope ! videoconvert ! x264enc ! flvmux name=mux ! queue ! fallbackswitch name=fswitch immediate-fallback=true 

//Audio Signal Branch 
tee. ! queue ! audioconvert ! audioresample ! capsfilter caps="audio/x-raw, channels=2, rate=32000" ! 
avenc_aac ! queue ! mux. 

// Secondary (Fallback) Image Source 
uridecodebin uri=file:///path/to/backup_image.jpg name=source_secondary ! 
imagefreeze ! queue ! videoconvert ! capsfilter caps="video/x-raw, width=1280, height=720, framerate=30/1" ! x264enc ! flvmux name=mux_image ! queue ! fswitch. 

// Output to RTMP 
fswitch. ! queue ! rtmp2sink location=rtmp://<your_rtmp_server>/live/stream

If there is any suggestion for using this fallbackswitch element or a description of the begaviour of it, I will be very grateful.
I've managed to use the fallbacksrc element and it's working properly, it's a very useful plugin for handling interruptions in gstreamer.
Thank you!

**Comment by sdroege** [comment]
This repository is just a mirror of https://gitlab.freedesktop.org/gstreamer/gstreamer-rs nowadays. But for your specific question, https://discourse.gstreamer.org is probably a better place to ask.
