### ISSUE TITLE
Add channel based helper for GstPlayer

### ISSUE THREAD

**Issue by sdroege** [sdroege/gstreamer-rs#24]
This would be instead of signals and, like GstBus allow polling in some thread to get an enum of all possibilities.

Should account for cancellation or injection of custom app messages, maybe tokio based?

@philn might this also be useful for you? I wanted to do something like this also in the C API but it's inconvenient to implement such things in C :p

See also https://bugzilla.gnome.org/show_bug.cgi?id=766898, let's just wait here and wrap a nice API around the C API later.

**Comment by philn** [comment]
Might be interesting to have yeah. Not sure yet if I need it though :)

**Comment by sdroege** [comment]
See https://bugzilla.gnome.org/show_bug.cgi?id=766898, let's just wait here and wrap a nice API around the C API later.

**Comment by 0xpr03** [comment]
Can't wait to have something like this.
Is there a way to make this with the current way of callbacks, to wrap them up inside futures ?

**Comment by sdroege** [comment]
I've replied to your mail about that :) yes, use a futures mpsc channel and put values of an enum you defined from the signal handler closures into the channel

**Comment by 0xpr03** [comment]
Oh nice idea.
I don't have any email :( To not spam this issue I'd also be available on IRC ( freenode #gstreamer ? )

**Comment by sdroege** [comment]
I guess that's t-online's dislike of personal mail servers then.

I'll be on irc there tomorrow afternoon

**Comment by philn** [comment]
I kinda wrote one there, fwiw https://github.com/philn/glide/blob/master/src/channel_player.rs
