### ISSUE TITLE
Question: tee, appsink and offset

### ISSUE THREAD

**Issue by fengalin** [sdroege/gstreamer-rs#29]
I tried implementing the `tee` [as you suggested](https://github.com/sdroege/gstreamer-rs/pull/22) and I'm nearly done. I have two problems left that are probably related.

For easier reference, this is the pipeline (for an audio only media):
```
             --- queue (visualization) --- audioconvert --- appsink (-> callback to visualization)
src --- tee /
            \
             --- queue (playback) --- audioconvert --- audioresample --- autoaudiosink
```

In my visualization, I want to display 1 sec of samples ahead of current position and 1 sec behind (this might change depending on the zoom factor). See [this screenshot](https://github.com/fengalin/media-toc/blob/master/assets/media-toc_audio.png) as an illustration. I read the tutorials on [multithreading](https://gstreamer.freedesktop.org/documentation/tutorials/basic/multithreading-and-pad-availability.html), [cutting the pipeline](https://gstreamer.freedesktop.org/documentation/tutorials/basic/short-cutting-the-pipeline.html) and [streaming](https://gstreamer.freedesktop.org/documentation/tutorials/basic/streaming.html) and ended up setting:
- source element (`uridecodebin`): `"buffer-duration"` property to 3 sec (as nano).
- visualization `queue`: `"max-size-time"` property to 3 sec (as nano). I believe the defaults for the other properties should be good as is (`"max-size-bytes"` being 10MB and `"max-size-buffers"` 200).
- visualization `queue`: `offset` to -1 sec (as nano).
- `appsink`: `offset` to -1 sec (as nano).

I checked the [appsink example](https://github.com/sdroege/gstreamer-rs/blob/master/examples/src/bin/appsink.rs) and implemented `appsink.set_callbacks` to get the samples. I first start my `pipeline` in the `Paused` state, so I defined both the `new_preroll` and `new_sample` closures.

#### Problem # 1
After the `pipeline` is set to `Paused`, I only get the first `sample` in the `new_preroll` closure. I also defined a pad probe on the `queue` `sink` which gives me the expected many buffers. So I guess the `appsink` doesn't pull the `buffers` during `preroll` even though they are available. I checked the [`properties` for `appsink`](https://github.com/GStreamer/gst-plugins-base/blob/master/gst-libs/gst/app/gstappsink.c), but the defaults seem to fit my needs.

What am I missing or doing wrong? I guess I would be better off implementing the visualization as a plugin, but it is supposed to be interactive and will be really tied up to the application.

#### Problem # 2
When I define the `offset` for the visualization `queue` and `appsink` to a value less than -1 sec (so further than 1 sec from 0), I no longer can get the `state` of the `pipeline` using `let (_, current, _) = self.pipeline.get_state(10_000_000);`. I tried larger values than 10 ms, but it didn't help.

#### Observation
Finally, not a show stopper but rather an observation. In the callbacks for pad probe or those from the `appsink`, the buffers' `offset` and `offset_end` are always equal and constant. According to [this page](https://gstreamer.freedesktop.org/documentation/design/overview.html#dataflow-and-buffers), I was expecting to be able to rely on them to get the position of the buffer in the stream. I searched in `gstreamer-rs`'s code, but found nothing suspicious there.

**Comment by sdroege** [comment]
You will only get the first sample in `new_preroll`, the one that you get while still in `Paused` (and also again another sample every time you go to `Paused`). You would use `pull_preroll_sample` for that one. Once `Playing`, you get the very same sample again in `new_sample` and all following ones only in `new_sample`. And would use `pull_sample` there.

For the offset, the reason here is that the queue by default takes up to 1s. You need to make both queues big enough for your needs. Otherwise one will run full, the other stays empty, and then the pipeline will never preroll. I'm not 100% sure what you mean with offset though. A pad offset? Why? You're trying to get the visualization 1s in advance before the audio?

Buffer offsets/offset_end are unfortunately not something you can rely on, unless you exactly know that the elements that are going to be used put the values in there that you expect.

**Comment by sdroege** [comment]
A better solution for that offset thing would be to have a big enough queue on the playback side, and use appsink with ts-offset or render-delay of 1s (or -1s?). Or an appsink with sync=false and you synchronize things yourself. But all these solutions would require you to have a big enough queue on the playback side.

**Comment by fengalin** [comment]
Ok, thanks! I'l try these and report back.

(As per the `offset`, I was referring to the pad's offset indeed).

**Comment by fengalin** [comment]
As you suggested, it works with the following:
- Large enough buffers for both queues.
- Setting `"ts-offset"` to -1.5 sec on the `appsink` (note: `"render-delay"` uses unsigned int).

I think I can live without rendering the samples in advance (while `Paused`).

Thanks again!

**Comment by sdroege** [comment]
If you want samples in Paused that can also be done. Or rather, you could have the vis appsink sync=false and in Playing while the other sink is Paused. You would then get at most as much data in Paused as the queue before the other sink can hold.

To manually manage the state of the vis sink, use set_locked_state(true). The bin won't change the state automatically anymore then (also not at shutdown!)

**Comment by fengalin** [comment]
Great! I'll try this. Many thanks.

**Comment by sdroege** [comment]
You probably also want async=false in addition to sync=false, and don't need the ts-offset anymore then.
