### ISSUE TITLE
Port all GStreamer tutorials

### ISSUE THREAD

**Issue by sdroege** [sdroege/gstreamer-rs#32]
Code can be found here: https://cgit.freedesktop.org/gstreamer/gst-docs/tree/examples/tutorials
Text with explanations here: https://gstreamer.freedesktop.org/documentation/tutorials/index.html

Would be nice to port these to Rust

**Comment by sdroege** [comment]
Start of this can be found here: https://github.com/sdroege/gstreamer-rs/tree/master/tutorials

Write here if someone wants to work on porting a specific tutorial

**Comment by Jouan** [comment]
I can try porting basic-tutorial-2.

**Comment by sdroege** [comment]
> I can try porting basic-tutorial-2.

That would be great, thanks! Let me know if you have questions

**Comment by sdroege** [comment]
basic-tutorial-2 is also done. Someone wants to do basic-tutorial-3? There's code in the examples that is almost like this already (decodebin.rs)

**Comment by sireliah** [comment]
Hey, I can try to write the third one. I'll use previous examples as a base.

**Comment by sdroege** [comment]
Thanks, that would be great :)

**Comment by sdroege** [comment]
Tutorial 3 is available here now: https://github.com/sdroege/gstreamer-rs/pull/38

**Comment by lovebug356** [comment]
I also tried basic-tutorial-4. The query part works, but it is not clear how to write GST_SEEK_FLAG_FLUSH | GST_SEEK_FLAG_KEY_UNIT in rust?

https://github.com/lovebug356/gstreamer-rs/commit/0c9d36d537f89069448b8e9871740015d6d6d704

**Comment by sdroege** [comment]
@lovebug356 This should work `gst::SeekFlags::FLUSH | gst::SeekFlags::KEY_UNIT` (if you use master, which uses bitflags 1.0. With 0.9 it was `gst::SEEK_FLAG_FLUSH` IIRC).

**Comment by lovebug356** [comment]
Fyi, I'm working on tutorial-6, but I'm struggling a bit with adding bindings for StaticPadTemplate (gir does not build on my system due to [a problem](https://github.com/alexcrichton/git2-rs/issues/263) with git2-rs).

**Comment by raytiley** [comment]
Figured I would comment on this issue rather than open a new one. Just looking into gstreamer, and have been wanting to a reason to learn a bit more about rust, so I figured I would check this project out.

I cloned the repo and ran `cargo build` inside the `tutorials` directory and received errors:

```
error: associated constants are experimental (see issue #29646)
   --> /Users/raytiley/.cargo/registry/src/github.com-1ecc6299db9ec823/bitflags-1.0.0/src/lib.rs:441:17
    |
441 |                 pub const $Flag: $BitFlags = $BitFlags { bits: $value };
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    | 
   ::: /Users/raytiley/.cargo/registry/src/github.com-1ecc6299db9ec823/bitflags-1.0.0/src/example_generated.rs
    |
4   | bitflags! {
    | - in this macro invocation

```

Can anyone point me in the right direction? Is there a "Getting Started" for these tutorials somewhere?

Thanks for any guidance.

**Comment by raytiley** [comment]
Ok.. so did some googling and figured out I had an outdated version of rust. Got everything to build but running `tutorial-1` panics.

```
🍻 RUST_BACKTRACE=1 ./basic-tutorial-1                                                                              master 08c30a0
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Boxed { inner: ForeignOwned(0x7ffba4d146a0) })', src/libcore/result.rs:906:4
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
   1: std::panicking::default_hook::{{closure}}
   2: std::panicking::default_hook
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic
   5: std::panicking::begin_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::result::unwrap_failed
   9: <core::result::Result<T, E>>::unwrap
  10: basic_tutorial_1::main
  11: __rust_maybe_catch_panic
  12: std::rt::lang_start
  13: main
```

**Comment by sdroege** [comment]
> Fyi, I'm working on tutorial-6, but I'm struggling a bit with adding bindings for StaticPadTemplate (gir does not build on my system due to a problem with git2-rs).

I can add it tomorrow if that helps, should be a matter of 5 minutes and boring :) You probably don't want to fight with libgit2 just for that :)

**Comment by sdroege** [comment]
@raytiley A backtrace with line numbers would be useful (and for the other thing, you need Rust 1.20 at least because of latest bitflags). My guess is that you're missing a GStreamer plugin or your GStreamer installation is otherwise incomplete/broken (the tutorial has no error handling at all to first focus on the actual GStreamer bits).

**Comment by raytiley** [comment]
> A backtrace with line numbers would be useful (and for the other thing, you need Rust 1.20 at least because of latest bitflags). My guess is that you're missing a GStreamer plugin or your GStreamer installation is otherwise incomplete/broken (the tutorial has no error handling at all to first focus on the actual GStreamer bits).

@sdroege I'll look into how to generate a more useful backtrace and confirm my gstreamer install. I'm on a mac and just used `brew install gstreamer`. Not sure  how to verify it installed properly but I'll poke around.

**Comment by sdroege** [comment]
@raytiley You also need at least gst-plugins-base and gst-plugins-good installed. I don't know if homebrew is splitting those up into separate plugins or have them as single packages with all the plugins.

**Comment by raytiley** [comment]
> You also need at least gst-plugins-base and gst-plugins-good installed. I don't know if homebrew is splitting those up into separate plugins or have them as single packages with all the plugins.

@sdroege Awesome! Thanks for helping out. I found the the other homebrew formulas.. (Also needed gst-libav for the codecs).

**Comment by sdroege** [comment]
@lovebug356 The bindings are there now, hopefully all that is needed https://github.com/sdroege/gstreamer-rs/commit/9206ddba611450a0cfb557f76dee946b0ae61c00 . Had to be written manually unfortunately due to those types being a bit special (no constructor, no copy/ref/free/unref, etc).

**Comment by sireliah** [comment]
I wrote wrote some code before https://github.com/sireliah/gstreamer-rs/commit/344f4ef576750c8e767db0d873e89e246851e3ad but I didn't have much time to finish it. Then I found you already have tutorial-3 ready here: https://github.com/sdroege/gstreamer-rs/blob/master/tutorials/src/bin/basic-tutorial-3.rs. Well, I guess that there is nothing more to do with third one?

**Comment by sdroege** [comment]
@sireliah If you have any suggestions for improving the existing tutorial, please submit a PR. I'm sure there are ways for making it nicer still :) Thanks for your effort in any case

Also it would be good if anybody working on another tutorial would write a short comment here so that people don't work on the same tutorial and duplicate work.

**Comment by sdroege** [comment]
This is now tracked at https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/issues/32
