### ISSUE TITLE
Rustdoc documentation is insufficient to use the library

### ISSUE THREAD

**Issue by pornel** [sdroege/gstreamer-rs#49]
The [link to the "documentation"](https://sdroege.github.io/rustdoc/gstreamer/gstreamer/) leads to a page is just a long list of… everything, in no particular order. There's no indication where to start, or what is important. It doesn't explain any concepts or how to do anything. The massive unorganized dump of entire API at once is overwhelming.

**Comment by sdroege** [comment]
It's only an API reference at this point, links to other documentation still has to be added. I'll add everything I write below to the README.md and also to the top of the rustdoc documentation later. Please let me know if there's anything else missing that would be good to have added.

For getting started, please take a look at the documentation on the GStreamer website for now: https://gstreamer.freedesktop.org/documentation/

The documentation there is explaining the concepts and how to use GStreamer from C, but the C documentation should be relatively easily be transferable to Rust. The API is basically the same in Rust, just with less noise and safer. Function names and objects are called the same.

For getting started I would recommend to read the (application development manual)[https://gstreamer.freedesktop.org/documentation/application-development/index.html] there first. Or doing the (tutorials)[https://gstreamer.freedesktop.org/documentation/tutorials/index.html]. Many tutorials were already ported to Rust and can be found (here)[https://github.com/sdroege/gstreamer-rs/tree/master/tutorials], and porting the remaining ones is probably a nice exercise also if you're interested in that.

**Comment by sdroege** [comment]
The above is now also in the README.md

**Comment by pornel** [comment]
Superb, thank you.

**Comment by sdroege** [comment]
If you're stuck somewhere nonetheless, please shout :)
