### ISSUE TITLE
How to run examples on macOS?

### ISSUE THREAD

**Issue by pornel** [sdroege/gstreamer-rs#50]
I've tried installing gstreamer via Homebrew, but Homebrew only has a generic "gstreamer" package, and not specific "gstreamer-video-1.0", etc.

I've also tried installing *everything* from https://gstreamer.freedesktop.org/data/pkg/osx/1.12.3/gstreamer-1.0-1.12.3-x86_64-packages.dmg and https://gstreamer.freedesktop.org/data/pkg/osx/1.12.3/gstreamer-1.0-1.12.3-x86_64.pkg

but in both cases gstreamer-rs can't find packages it needs:

> /gstreamer-rs/examples$ cargo run --bin playbin
   Compiling gstreamer-audio-sys v0.3.0 (https://github.com/sdroege/gstreamer-sys#4b228f5f)
   Compiling gstreamer-app-sys v0.3.0 (https://github.com/sdroege/gstreamer-sys#4b228f5f)
   Compiling gstreamer-video-sys v0.3.0 (https://github.com/sdroege/gstreamer-sys#4b228f5f)
error: failed to run custom build command for `gstreamer-app-sys v0.3.0 (https://github.com/sdroege/gstreamer-sys#4b228f5f)`
process didn't exit successfully: `/www/gstreamer-rs/target/debug/build/gstreamer-app-sys-5e59631e4f8c2493/build-script-build` (exit code: 1)
--- stderr
`"pkg-config" "--libs" "--cflags" "gstreamer-app-1.0 >= 1.8"` did not exit successfully: exit code: 1
…
`"pkg-config" "--libs" "--cflags" "gstreamer-audio-1.0 >= 1.8"` did not exit successfully: exit code: 1
…
`"pkg-config" "--libs" "--cflags" "gstreamer-video-1.0 >= 1.8"` did not exit successfully: exit code: 1

**Comment by sdroege** [comment]
I'll reply with details/instructions here and to your other github issue tomorrow. Sorry for the problems to get started!

**Comment by sdroege** [comment]
I'll also add this (and the same for Windows and Linux/BSD) to the README.md and rustdocs later.

On macOS you have two ways of getting GStreamer. Either installing the binaries from the GStreamer website, which come with everything needed at once and provide a .framework, or via homebrew. For homebrew you need to install gstreamer and at least gst-plugins-base, probably also gst-plugins-good/gst-plugins-bad/gst-plugins-ugly/gst-libav (or however they call it, please let me know).

Once you have that, you need to make sure that the directory with the file `gstreamer-1.0.pc` is in one of the directories pointed to by the `PKG_CONFIG_PATH` environment variable (or in the default search path of your `pkg-config`, which should be correct already in the case of homebrew). In case of the GStreamer binaries this is in GStreamer.framework/lib/pkgconfig (iirc, please correct me, I don't have a mac here currently. Might also have been GStreamer.framework/Versions/Current/lib/pkgconfig or similar).

After that it should be possible to build and use the bindings.

**Comment by pornel** [comment]
Thank you for your response. 

I've got `/Library/Frameworks/GStreamer.framework` (from pkg installer from the official site), but there are no `.pc` files anywhere in it. I also didn't find any `gs*.pc` files in `/usr`.

I have `/Library/Frameworks/GStreamer.framework/Versions/1.0/lib/` with lots of `*dylib` files, but no sign of pkgconfig. Perhaps you could use that as as a library search path without relying on pkgconfig?

**Comment by sdroege** [comment]
Do you have installed the devel and non-devel variant? If you do and the pc files are not there, they need to be added.

I would suggest using homebrew for simplicity for now in that case and I'll get them added for the next GStreamer release.

**Comment by pornel** [comment]
I haven't noticed there are two versions. I've installed https://gstreamer.freedesktop.org/data/pkg/osx/1.12.3/gstreamer-1.0-1.12.3-x86_64-packages.dmg and https://gstreamer.freedesktop.org/data/pkg/osx/1.12.3/gstreamer-1.0-1.12.3-x86_64.pkg

**Comment by sdroege** [comment]
There are even 3, it's also hidden in the docs what they mean.

You need both .pkg files. The one you already have and one with -devel at the end of the filename. The DMG contains separate pkgs for each component, that you then could directly embed into your application's pkg

**Comment by pornel** [comment]
With the -devel package and/or gst-plugins-good/gst-plugins-bad I've got it to compile. Thank you for your help.

**Comment by sdroege** [comment]
Thanks, I'll update the README accordingly later

**Comment by sdroege** [comment]
Can you check if the installation instructions in the README.md for macOS are what you did? Thanks :)

**Comment by nleco** [comment]
I've tried and got the code to compile. I've tried installing the packages and also via homebrew. However, when I run the program, it just hangs and nothing shows up.

**Comment by sdroege** [comment]
The GitHub repository is only a mirror. Please report any bugs [here](https://gitlab.freedesktop.org/gstreamer/gstreamer-rs) and if it's not necessarily a bug and you just need support please use the [mailing list](https://lists.freedesktop.org/mailman/listinfo/gstreamer-devel).

**Comment by sdroege** [comment]
See [above](https://github.com/sdroege/gstreamer-rs/issues/50#issuecomment-465897709), and also this repository is for the Rust bindings of GStreamer and you're having problems with compiling C code.

**Comment by saifeiLee** [comment]
> I'll reply with details/instructions here and to your other github issue tomorrow. Sorry for the problems to get started!

Same here. Any suggestion please?

**Comment by saifeiLee** [comment]
> Working on Mac OS Big Sur, I have tried to install with `brew install gstreamer` (along with `gst-plugins-common`,`gst-plugins-good`). I then try to compile the first example at https://gstreamer.freedesktop.org/documentation/tutorials/basic/hello-world.html?gi-language=c and this is how far I come:
> 
> ```
> ➜  gcc basic-tutorial-1.c
> basic-tutorial-1.c:1:10: fatal error: 'gst/gst.h' file not found
> #include <gst/gst.h>
>          ^~~~~~~~~~~
> 1 error generated.
> ```
> 
> And another attempt, where I point out the include files:
> 
> ```
> ➜ gcc basic-tutorial-1.c -I/usr/local/Cellar/gstreamer/1.18.5/include/gstreamer-1.0/
> In file included from basic-tutorial-1.c:1:
> /usr/local/Cellar/gstreamer/1.18.5/include/gstreamer-1.0/gst/gst.h:27:10: fatal error: 'glib.h' file not found
> #include <glib.h>
>          ^~~~~~~~
> 1 error generated.
> ```
> 
> Looks like I'm far from being able to compile this. What steps am I missing?

Same here. Any suggestion please?

**Comment by sdroege** [comment]
> Same here. Any suggestion please?

I suggest reading the comments, like https://github.com/sdroege/gstreamer-rs/issues/50#issuecomment-998855926 . You're commenting in the wrong place.

**Comment by saifeiLee** [comment]
> > Same here. Any suggestion please?
> 
> I suggest reading the comments, like [#50 (comment)](https://github.com/sdroege/gstreamer-rs/issues/50#issuecomment-998855926) . You're commenting in the wrong place.

Thanks for your suggestion~
