### ISSUE TITLE
Tutorial 6 on macOS: 'G_IS_VALUE (value)' failed

### ISSUE THREAD

**Issue by pornel** [sdroege/gstreamer-rs#61]
```sh
cargo run --bin basic-tutorial-6
```

> Pad Template for Audio test source:
  SRC template: 'src'
  Availability: Always
  Capabilities:
    audio/x-raw

> (process:78002): GLib-GObject-CRITICAL **: g_strdup_value_contents: assertion 'G_IS_VALUE (value)' failed
> thread 'main' panicked at 'assertion failed: !ptr.is_null()', /Users/porneL/.cargo/git/checkouts/glib-928cf7b282977403/4356d43/src/translate.rs:872:8

Backtrace points to src/bin/basic-tutorial-6.rs:20

```rust
        for (field, value) in structure.iter() {
            println!("{}  {}:{:?}", prefix, field, value);
        }
```

**Comment by sdroege** [comment]
See https://github.com/sdroege/gstreamer-rs/issues/58#issuecomment-343722297 . This might be the same problem, but I'm not entirely sure with this one.

Can you also set `G_DEBUG=fatal_warnings` in the environment and get a backtrace (see the other comment) from the `G_IS_VALUE` warning? If you run in lldb it should stop at the warning.

Also please paste the full backtrace from Rust too

**Comment by philn** [comment]
No issue here with this tutorial. Works as expected with the .pkgs.

**Comment by pornel** [comment]
Yup, my installation was cursed. It runs after reinstall of gstreamer.
