### ISSUE TITLE
player: how to create a PlayerConfig?

### ISSUE THREAD

**Issue by philn** [sdroege/gstreamer-rs#74]
Perhaps I'm still too new to this but it's really not obvious to me :)

**Comment by sdroege** [comment]
You get the config from a player and modify it :)

**Comment by sdroege** [comment]
[This](https://sdroege.github.io/rustdoc/gstreamer/gstreamer_player/struct.Player.html#method.get_config) one btw

**Comment by philn** [comment]
Ah, that makes sense indeed. I was trying to create one from scratch.
