### ISSUE TITLE
Does this crate support android?

### ISSUE THREAD

**Issue by ArmsOfSorrow** [sdroege/gstreamer-rs#89]
I know that the underlying gstreamer library supports it, but what's the story for this crate?

**Comment by sdroege** [comment]
It should work just fine on Android, there's no platform dependent code inside the crate itself. I never tried it on Android (or iOS for that matter) though.

If you run into any problems please let me know!

**Comment by sdroege** [comment]
@ArmsOfSorrow Any progress with trying it already, anything you need help with?

**Comment by ArmsOfSorrow** [comment]
Not at the moment. It was more of a "can it be done" type of question because I have a bit of code written in C from an earlier project and I'm thinking about whether redoing some parts of that is a good way to further learn Rust.

If there's a problem I run into I'll let you know.

On Mar 6, 2018 5:09 PM, Sebastian Dröge <notifications@github.com> wrote:

@ArmsOfSorrow<https://github.com/armsofsorrow> Any progress with trying it already, anything you need help with?

**Comment by sdroege** [comment]
Great, thanks! Let's close this for now then

**Comment by alanpoon** [comment]
i am trying cross compile to andoidabi target. I got this error. 
/usr/local/android-ndk-r15b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lglib-2.0
          collect2: error: ld returned 1 exit status
          Error while executing gcc

**Comment by sdroege** [comment]
You'll have to provide some more information about what you do and how, but this seems unrelated to this crate in any case and a general setup problem.

Please provide a way to reproduce this, and I'll try to take a look in the next days

**Comment by alanpoon** [comment]
Hi, here is output of my circleci setup.
https://circleci.com/gh/alanpoon/cpal/136

**Comment by sdroege** [comment]
It doesn't look like you get GStreamer for Android anywhere there, you only install the system Linux packages.

You'd ideally get the GStreamer binaries from the GStreamer website, then integrate that with your Android app build (see the docs there). And then you need to make sure that `glib-sys`, `gobject-sys`, `gstreamer-sys`, etc. are using the correct library (`libgstreamer_android.so` for all of them) as generated by the GStreamer build system.

**Comment by ferjm** [comment]
For reference, I replied in https://github.com/servo/libgstreamer_android_gen/issues/2#issuecomment-427313001
