### ISSUE TITLE
Building on Windows x64 with MSVC not working

### ISSUE THREAD

**Issue by ArmsOfSorrow** [sdroege/gstreamer-rs#90]
Hello,

I wanted to write a simple program that just reports the linked gstreamer version. It looks like this:
```
fn main() {
    let version = gstreamer::version_string();
    println!("Hello, world! You're using {}", version);
}
```

The build fails with:
```
error: failed to run custom build command for `glib-sys v0.5.0`
process didn't exit successfully: `C:\Users\waved\Desktop\devel\projects\gst-print-version\target\debug\build\glib-sys-04fcb8127bd3b7bb\build-script-build` (exit code: 1)
--- stderr
MSVC target detected. If you are using the MSVC ABI rust build, please use the GNU ABI build instead.
```

Now, this is not a gstreamer bug per se, but I'm curious why I can't build this with the recommended default toolchain for my platform.

**Comment by sdroege** [comment]
The problem is that the Rust `pkg-config` crate is not (yet) compatible with MSVC: https://github.com/alexcrichton/pkg-config-rs/blob/5203aff8b20479c9df159be2efb4162450019330/src/lib.rs#L228-L230

See https://github.com/alexcrichton/pkg-config-rs/issues/59

**Comment by sdroege** [comment]
This is now fixed https://github.com/alexcrichton/pkg-config-rs/pull/70
