### ISSUE TITLE
Add bindings for GstSDPMessage and others, and the WebRTC library

### ISSUE THREAD

**Issue by sdroege** [sdroege/gstreamer-rs#97]
A WIP branch can be found here: https://github.com/sdroege/gstreamer-rs/tree/webrtc-sdp

Main thing that is missing at this point is to add bindings for GstSDPMessage, which unfortunately have to be fully manually written.

**Comment by sdroege** [comment]
@fengalin would this be something you'd be interested in? After that the demos from https://github.com/centricular/gstwebrtc-demos/ could be ported to Rust :)

**Comment by fengalin** [comment]
Yes! Thank you for proposing. I'll take a look at it later this week or next week.

**Comment by notbdu** [comment]
No idea what I'm doing but I would also like to contribute here as well.

**Comment by notbdu** [comment]
Isn't `GstSdpMessage` defined in `./gstreamer-sdp-sys/src/lib.rs`? Not sure what exactly needs to be done here. 

Also, after looking at the gst webrtc demo code... it looks like it uses libsoup for the HTTP client. Would the ported example just use a rust HTTP client (e.g. hyper)?

**Comment by sdroege** [comment]
> Isn't GstSdpMessage defined in ./gstreamer-sdp-sys/src/lib.rs? Not sure what exactly needs to be done here.

It is only currently available in the -sys crate, not the safe non-sys crate.

> Also, after looking at the gst webrtc demo code... it looks like it uses libsoup for the HTTP client. Would the ported example just use a rust HTTP client (e.g. hyper)?

Yes, not sure if hyper supports WebSockets already but there are also crates for WebSockets.

**Comment by notbdu** [comment]
Ooo okay, thanks!

**Comment by notbdu** [comment]
Hmmm, I see that `SDPMessage` is already auto generated by gir in `gstreamer-sdp/src/auto/s_d_p_message.rs`. But there's another non autogenerated file here `src/s_d_p_message.rs`.

Are they different? The auto generated seems to be for the same struct defined in the -sys crate.

**Comment by sdroege** [comment]
The autogenerated one should disappear as this type can't really be autogenerated for any of the functions. And then the manual one should get proper bindings for each of the functions that a) use the correct types, b) have correct ownership handling, and c) handle return values correctly

In addition all the types used by `GstSDPMessage` would have to be generated, like `GstSDPMedia` for example.

**Comment by notbdu** [comment]
Okay, got it. I'll take a crack at it today :). Thank you for the guidance @sdroege!

**Comment by notbdu** [comment]
Btw, just curious. How come this type can't be autogenerated. I'm new to gir so I don't really have any knowledge of what's doable/not doable.

**Comment by sdroege** [comment]
If you check the above 3 points, you'll see :) It's a very non GI-compatible API unfortunately, it does not follow any of the API conventions GI requires.

**Comment by notbdu** [comment]
My _probably_ misguided attempt at a manual `SDPMessage` defintion:
https://github.com/sdroege/gstreamer-rs/pull/100

I ended up implementing only the commented out methods. I looked over the uncommented autogen'ed methods and they _seemed_ alright to me in terms of type/ownership handling.

**Comment by fengalin** [comment]
It seems you already spent quite some times on this stuff @notbdu, so I let it go.

**Comment by sdroege** [comment]
@fengalin There are a few other things in the issues list if you want to take on something else :)

**Comment by fengalin** [comment]
Sure! We also talked about https://github.com/sdroege/gst-plugin-rs/issues/21 before. I'll start working on it shortly.

**Comment by sdroege** [comment]
This is now all done :)
