### ISSUE TITLE
Tutorial 3 does not work on OSX

### ISSUE THREAD

**Issue by ferjm** [sdroege/gstreamer-rs#98]
Tutorial 3 does not play any audio and breaks with this output on OSX:

```bash
❯ ./target/debug/basic-tutorial-3
Pipeline state changed from Null to Ready
Received new pad src_0 from test-pipeline
It has type video/x-raw which is not raw audio. Ignoring.
Error received from element Some("/GstPipeline:test-pipeline/GstURIDecodeBin:source/GstSoupHTTPSrc:source") Internal data stream error.
Debugging information: Some("gstbasesrc.c(2939): void gst_base_src_loop(GstPad *) (): /GstPipeline:test-pipeline/GstURIDecodeBin:source/GstSoupHTTPSrc:source:\nstreaming stopped, reason not-linked (-1)")
```

It works perfectly fine on Linux.

**Comment by sdroege** [comment]
That means that for some reason the video pad is never appearing in the pad probe but also not connected. Which suggests that a decoder was not found for it... can you confirm?

**Comment by sdroege** [comment]
Or alternatively attach a debug log here and I'll take a look :) The problem here is likely caused by the tutorial being a bit too simplified and not catching all possible error cases gracefully.

**Comment by ferjm** [comment]
Yes, it seems that the decoder was not found:

<details>
❯ GST_DEBUG=WARNING ./target/debug/basic-tutorial-3
Pipeline state changed from Null to Ready
0:00:01.144739000 63303 0x7fe030835ad0 WARN            uridecodebin gsturidecodebin.c:931:void unknown_type_cb(GstElement *, GstPad *, GstCaps *, GstURIDecodeBin *):<source> warning: No hay un decodificador disponible para el tipo «audio/x-vorbis, channels=(int)2, rate=(int)48000, streamheader=(buffer)< 01766f72626973000000000280bb0000000000008038010000000000b801, 03766f726269731d000000586970682e4f7267206c6962566f726269732049203230303930373039010000001a000000454e434f4445523d66666d706567327468656f72612d302e323401, 05766f7262697321424356010000010018635429469952d24a8919739431469962924a89a5841642489d731453a939d79c6bacb9b52084101a5350290599528e526919639029059952104b492574123a279d63105b49c1d6986b8b41b61c840d9a524c29c494528a420819538c29c594524a420725740e3ae61c538e4a2841b89c73abb59696638ba974924ae724644c42482985924a07a5534e42483596d652291d7352526a41e820841042b620840d82d0905500000100c040101ab20a00500000108aa1188a028486ac020032000004a0288ee2288e233992634916101ab20a00000200100000c07014499114c9b1244bd22c4bd34451557dd5365555f6755dd7755dd77520346415000001004048a799a51a20c20c6418080d590500200000004628c210034243560100000100006228398826b4e67c738e836639682ac5e6747022d5e6496e2ae6e69c73ce39279b73c638e79c738a7266316826b4e69c73128366296826b4e69c739ec4e6416baab4e69c73c639a783714618e79c739ab4e6416a36d6e69c7316b4a6396a2ec5e69c7322e5e6496d2ed5e69c73ce39e79c73ce39e79c73aa17a773704e38e79c73a2f6e65a6e4217e79c733e19a77b734238e79c73ce39e79c73ce39e79c7382d0905500001000004118368671a720489fa38118458869c8a407dda3c324680c720aa947a3a39152ea209454c649299d20346415000008000021841452482185145248218514528821861862c829a79c820a2aa9a4a28a32ca2cb3cc32cb2cb3cc32ebb0b3ce3aec30c410430cadb4124b4db5d55863adb9e79c6b0ed25a69adb5d64a29a594524a29080d59050080000010081964904146218514528821a69c72ca29a8a0024243560100800000020000003cc97344477444477444477444477444c7733c47944449944449b44ccbd44c4f1555d5955d5bd665ddf66d611776ddf775dff775e3d785615996655996655996655996655996655982d09055000008000080104208218514524821a51863cc31e7a0935042203464150000080020000000c0511cc57124477224c9922c4993344bb33ccdd33c4df44451144dd35445577445ddb445d9944dd7744dd9745559b55d59b66dd9d66d5f966ddff77ddff77ddff77ddff77ddff7751d080d590500480000e8488ea4488aa4488ee338922401a121ab00001900000100288aa3388ee34892244996a4499ee559a2666aa6677aaaa802a121ab0000400000010000000000289ae229a6e229a2e239a2234aa2655aa2a66aae289bb2ebbaaeebbaaeebbaaeebbaaeebbaaeebbaaeebbaaeebbaaeebbaaeebbaaeebbaaeebba2e101ab20a00900000d0911cc9911c49911449911cc90142435601003200000200700cc79014c9b12c4bd33ccdd33c4df4444ff44c4f155dd10542435601008000000200000000003024c3522c4773344994544bb5544db5544b15554f555555555555555555555555555555555555555555555555555555555555555555354dd3344d203464250010050040396cb1e6de1b6198721473698c538e6a509142ca590d2a420a3189bd55cc312731c7ce31e6a4e59c318418b49a3ba714739202a1212b0480d00c0087e30092660192a50100000000000080a46980e67980e6790000000000000020691aa0791ea0791e00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008ea6019ae7019ae70100000000000080e67980279a80278a0000000000000060791ee0891ee0892200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008ea6019ae7019a270200000000000080e57980678a80e78900000000000000a0791ee08922e0892200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008000008000070080000ba1d0901501409c008043712c0900001cc7b12c0000701cc9b20000c0b22ccf030000cbb23c0f00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000400000c080030040800965a0d0909500401400804131340dc8b26501976501340da069004f04781e4035018000008002070080001b3425160728346425001005006050144bb22ccf83a6699a2842d3344d14a1699e679ad034cf334d88a2e799263ccff34c13a6298aaa0a4451550500001438000004d8a029b13840a1212b018090000083a35896a6799ee789a269aa2a34cdf34451144dd33455159ae679a2288aa6699aaa0a4df33c511445d354555585a6799e288aa269aaaaabc2f34451344dd33455d575e179a2688aa6699aaaeaba104551344dd35455d7755d208aa6699aaaeabaae0b44d1344d55555d579681289aa669aaaaebca32304dd35455d7755d590698a6aabaaeebca3240555dd77565599601aaaaaaae2bcbb20c705dd7755d59b66d00aeebbab26cdb0200000e1c0000028ca0938c2a8bb0d1840b0f40a1212b0280280000c018a61453ca302621a4101ac6248414422525a5944aa920a4525229158454522a25a392526a296510522929950a4229a595540000d8810300d881855068c84a00200f0080204429c618734e4aa91463ce3927a5548a31e79c935232c69873ce49291963cc39e7a4948c39e79c73524ac69c73ce3929a573ce39e79c94524ae79c734e4a292584ce3927a594d239e79c13000054e000001060a3c8e60423418586ac04005201000c8e63599aa6699e678a9a64699ae7799e289aa626499ae6799e278aa6c9f33c4f1445d1345593e7799e288aa269aa2ad71545d1344d555555b22c8aa2689aaaaaaa304dd3545557755d98a629aaaaabca2e64d93455d5756519b66d9aaaeabab20c5457555dd79681abaaaa6cdab20000f0040700a0021b564738291a0b2c3464250090010040108290520a21a514424a2984945208090000187000000830a10c141ab21200480500000c91524a29a594d23825a594524a29a5714c4a29a594524a29a594524a29a594524a29a594524a29a594524a29a594524a29a594524a29a594524a29a594524a29a594524a29a594524a29a594524a29a594524a29a594524a29a594524a29a594524a29a594524a2905002e553800e83ed8b03ac249d15860a1212b0180540000c018851883504a6b15428c3927a5a5d62a8418734e4a4aade58c390721a5d662cb9d730c4229adc5d853e99c94945a8bb1a7143a2a29b5165befbda4925a6b2dc6de7b0a29d4d65a8cbdf756536b2dc61a7bef39b6124bac31f6de7b8fb5c5d862ecbdf71e5b4bb5e55800006683030044820dab239c148d05161ab21200080900208c514a29c69c73ce39e7a4948c31e61c84104208a1949231c79c8310420821945232e69c831042082584524ac69c830e420825845252ea9c73104208a184504a299d730e42082184504a4aa9731042082184104a2925a5d43908219410420829a5944208218410420821959252082184104228a59454520a2184104208a58452524a2985104a08218450524a29a5524a092184104a4a29a5144a08219410424a29a5944a092184104a48a9a494524921841042080500001c3800000418412719551661a309171e80424356020051000010821242492d02482926ad86483927add61239a41cc51a22a6949396420699524c4a092d748c494b29b6123a48a9e61c5308290000008200800013406080a0e00b2120c6000004213243241456c102833268709807000f1011120140628222ede202ba0c704117771d08210841086271000524e0e0841b9e78c3136e70824e51a90301000000005800800700008402888868e62a2c2e30323436383a3c3e400400000000c00a003e000090102022a299abb0b8c0c8d0d8e0e8f0f8000900000410000000000001042020200000000000100000002020 >».
Received new pad src_0 from test-pipeline
It has type video/x-raw which is not raw audio. Ignoring.
0:00:01.300108000 63303 0x7fe03183d850 WARN                 basesrc gstbasesrc.c:2939:void gst_base_src_loop(GstPad *):<source> error: Internal data stream error.
0:00:01.300170000 63303 0x7fe03183d850 WARN                 basesrc gstbasesrc.c:2939:void gst_base_src_loop(GstPad *):<source> error: streaming stopped, reason not-linked (-1)
Error received from element Some("/GstPipeline:test-pipeline/GstURIDecodeBin:source/GstSoupHTTPSrc:source") Internal data stream error.
Debugging information: Some("gstbasesrc.c(2939): void gst_base_src_loop(GstPad *) (): /GstPipeline:test-pipeline/GstURIDecodeBin:source/GstSoupHTTPSrc:source:\nstreaming stopped, reason not-linked (-1)")
</details>

**Comment by sdroege** [comment]
Curious! Does `gst-inspect-1.0 vorbisdec` show anything? Do you have `libgstvorbis.{dylib,so}` somewhere in your GStreamer installation?

**Comment by ferjm** [comment]
`gst-inspect-1.0` does not find `vorbisdec` and I have no `libgstvorbis.{dylib,so}` :\

In reinstalled GStreamer dependencies via Homebrew.

<details>
==> Downloading https://homebrew.bintray.com/bottles/gstreamer-1.14.0_1.high_sierra.bottle.tar.gz
Already downloaded: /Users/ferjm/Library/Caches/Homebrew/gstreamer-1.14.0_1.high_sierra.bottle.tar.gz
==> Pouring gstreamer-1.14.0_1.high_sierra.bottle.tar.gz
==> Caveats
Consider also installing gst-plugins-base and gst-plugins-good.

The gst-plugins-* packages contain gstreamer-video-1.0, gstreamer-audio-1.0,
and other components needed by most gstreamer applications.
==> Summary
🍺  /usr/local/Cellar/gstreamer/1.14.0_1: 415 files, 21.5MB
==> Downloading https://homebrew.bintray.com/bottles/gst-plugins-base-1.14.0_1.high_sierra.bottle.tar.gz
Already downloaded: /Users/ferjm/Library/Caches/Homebrew/gst-plugins-base-1.14.0_1.high_sierra.bottle.tar.gz
==> Pouring gst-plugins-base-1.14.0_1.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/gst-plugins-base/1.14.0_1: 612 files, 21.9MB
==> Downloading https://homebrew.bintray.com/bottles/gst-plugins-good-1.14.0.high_sierra.bottle.tar.gz
Already downloaded: /Users/ferjm/Library/Caches/Homebrew/gst-plugins-good-1.14.0.high_sierra.bottle.tar.gz
==> Pouring gst-plugins-good-1.14.0.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/gst-plugins-good/1.14.0: 470 files, 13.9MB
==> Downloading https://homebrew.bintray.com/bottles/gst-plugins-bad-1.14.0.high_sierra.bottle.tar.gz
Already downloaded: /Users/ferjm/Library/Caches/Homebrew/gst-plugins-bad-1.14.0.high_sierra.bottle.tar.gz
==> Pouring gst-plugins-bad-1.14.0.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/gst-plugins-bad/1.14.0: 687 files, 18.4MB
==> Downloading https://homebrew.bintray.com/bottles/gst-plugins-ugly-1.14.0.high_sierra.bottle.tar.gz
Already downloaded: /Users/ferjm/Library/Caches/Homebrew/gst-plugins-ugly-1.14.0.high_sierra.bottle.tar.gz
==> Pouring gst-plugins-ugly-1.14.0.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/gst-plugins-ugly/1.14.0: 91 files, 1.5MB
==> Downloading https://homebrew.bintray.com/bottles/gst-libav-1.14.0.high_sierra.bottle.tar.gz
Already downloaded: /Users/ferjm/Library/Caches/Homebrew/gst-libav-1.14.0.high_sierra.bottle.tar.gz
==> Pouring gst-libav-1.14.0.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/gst-libav/1.14.0: 32 files, 13MB
==> Downloading https://homebrew.bintray.com/bottles/gst-rtsp-server-1.14.0_1.high_sierra.bottle.tar.gz
Already downloaded: /Users/ferjm/Library/Caches/Homebrew/gst-rtsp-server-1.14.0_1.high_sierra.bottle.tar.gz
==> Pouring gst-rtsp-server-1.14.0_1.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/gst-rtsp-server/1.14.0_1: 38 files, 1.5MB
</details>


But still no `libgstvorbis.{dylib,so}`.

**Comment by sdroege** [comment]
Ah you're using homebrew. It probably is in a different "formulae" (was that the word they use?) to be installed, or maybe a different configuration to be used. In theory the Vorbis plugin is in gst-plugins-base.

**Comment by ferjm** [comment]
Right, `libvorbis` is [optional](https://github.com/Homebrew/legacy-homebrew/blob/49a14193482a9f0ec95cab78dcc528bccebdafea/Library/Formula/gst-plugins-base.rb#L35) in `gst-plugin-base` so installing it with `brew install gst-plugins-base --with-libvorbis` made the trick.

Do you want me to update the README to add this flag? Should the other optional deps be installed as well (orc, gtk+, libogg, pango, theora)?

**Comment by sdroege** [comment]
That would be good, yes. All those dependencies except for GTK. Thanks! And maybe add a comment that the other GStreamer related things in homebrew also only install various plugins if explicitly enabled.

**Comment by ferjm** [comment]
Done.

Thanks for your help! :)
